// Redux Action Types
export const actionTypes = {
  SET_COINS: 'SET_COINS',
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  ADD_TO_WATCHLIST: 'ADD_TO_WATCHLIST',
  REMOVE_FROM_WATCHLIST: 'REMOVE_FROM_WATCHLIST',
  UPDATE_HOLDINGS: 'UPDATE_HOLDINGS',
  UPDATE_WATCHLIST_DATA: 'UPDATE_WATCHLIST_DATA',
  SET_SELECTED_COINS: 'SET_SELECTED_COINS',
  CLEAR_SELECTED_COINS: 'CLEAR_SELECTED_COINS'
};